---
title: "Voter Fraud!? | A Reimagining of Precinct Matching for Analyzing Absentee Ballots in the 2020 Presidential Election"
author: "Sean J. Birch"
date: "DRAFT `r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
header-includes: 
   - \usepackage{wrapfig}
   - \usepackage{caption}
---

\captionsetup[figure]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r}
# Required packages
library(tidyverse)
library(sf)
library(dplyr)
library(rgeos)
library(rgdal)
library(gridExtra)
library(viridis)

library(pdftools)
library(readxl)
library(janitor)
library(stringr)

library(tidycensus)
tidycensus::census_api_key("5f98a6c74bd7ae588481b45d22d48b487611ab89")

library(stargazer)
```

# Fulton, GA
## GA Precinct Matching (DEV)
```{r }
# Fulton County, Georgia

# Setting parameters and loading spatial data: Allegheny County, Pennsylvania

county_shapefile <- "tl_2021_us_county"
precinct_shapefile <- "GA/GA_Precinct"
county_code <- "121"
State_fips <- 13
County_GEOID <- 13121

CRS <- 4326 # Doesn't appear to matter; but needs to be consistent for matching to work
poly2nb_snap <- 0.0005 # Tangent geometry snapping constant

BlockGroup_shapefile = "GA/GA_2020_Blockgroup"
BlockGroup_data_file = "GA/census_BlockGroup_data_GA.xlsx" # Census block group data file name

us_county <- sf::st_read(county_shapefile) # County shape file for exterior matching
us_county_OGR <- sf::as_Spatial(us_county) # Spatial polygon copy needed for certain functions to work

State_Precinct <- sf::st_read(precinct_shapefile) %>%
  dplyr::mutate(COUNTYFP20 = substr(DISTRICT, start = 1, stop = 3)) %>% 
  dplyr::rename(GEOID20 = ID)

State_Precinct_County <- State_Precinct %>% # Subsetting specific county: Allegheny
    subset(COUNTYFP20 == county_code)

set.seed(2020)
```

```{r }
# Identify adjacent counties: tangent to Fulton

us_county_state <- us_county %>%  # Subsetting state's county level geometries: Georgia
  subset(STATEFP == State_fips)
row.names(us_county_state) <- NULL # Row numbers needed to be resequenced

us_county_state_OGR <- us_county_OGR %>% # Subsetting state's county level geometries in Spatial polygon
  subset(STATEFP == State_fips)

us_county_state_Adjacent_Matrix <- us_county_state_OGR %>% # Create logical matrix of which geometries are tangent
  rgeos::gTouches(byid=TRUE)
rownames(us_county_state_Adjacent_Matrix) <- us_county_state$GEOID # IDs set to match County shapefile
colnames(us_county_state_Adjacent_Matrix) <- us_county_state$GEOID

# Adjacent County geometry
Adjacent_County_Geometry <- us_county_state[which( # subsetted adjacent counties: tangent to Allegheny
  as.data.frame(us_county_state_Adjacent_Matrix)[,which(us_county_state$GEOID == County_GEOID)]
  ),] %>% 
  dplyr::select(GEOID, geometry, COUNTYFP) # Only necessary variables

# Standardized columns
State_Precinct_County_GEO <- State_Precinct_County %>% # Standardized columns for combination
  dplyr::rename(GEOID = GEOID20, COUNTYFP = COUNTYFP20) %>%
  dplyr::select(GEOID, geometry, COUNTYFP)

row.names(Adjacent_County_Geometry) <- NULL
row.names(State_Precinct_County_GEO) <- NULL
```

```{r }
# crs transformation (prevents errors)
Adjacent_County_Geometry_crs <- st_transform(Adjacent_County_Geometry, crs = CRS)
State_Precinct_County_GEO_crs <- st_transform(State_Precinct_County_GEO, crs = CRS)

# Combine precinct and county files into one
Precinct_and_County_Spatial <- rbind(Adjacent_County_Geometry_crs, State_Precinct_County_GEO_crs) %>% 
  sf::as_Spatial()

# Creates list of adjacent geometries - then subsided and formatted
Adjacent_List_Interior <- spdep::poly2nb(sp::as.SpatialPolygons.PolygonsList(Precinct_and_County_Spatial@polygons), 
                                         snap = poly2nb_snap)

Num_Adjacent_County <- nrow(Adjacent_County_Geometry_crs) # poly2nb creates nested list for each polygon - Only need exterior
In_Index <- numeric()
for(i in 1:Num_Adjacent_County){ # loop through the first three sub-lists and combine indices
  In_Index <- c(In_Index, Adjacent_List_Interior[[i]])
}
In_Index <- In_Index[In_Index > Num_Adjacent_County] # Exterior counties removed

Precinct_Interior <- rbind(Adjacent_County_Geometry_crs, State_Precinct_County_GEO_crs)[In_Index,] # Filtering interior border precincts

ggplot() +
  geom_sf(data = Precinct_Interior, color = "black", fill = "gray90") +
  geom_sf(data = subset(us_county,GEOID == County_GEOID), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  theme(legend.position = "none")
```

```{r }
# Selecting precincts in exterior counties

State_Precinct_County_GEO_Exterior <- State_Precinct %>% # Subset precincts in adjacent counties
  subset(COUNTYFP20 %in% Adjacent_County_Geometry$COUNTYFP) %>%
  dplyr::rename(GEOID = GEOID20, COUNTYFP = COUNTYFP20) %>%
  dplyr::select(GEOID, geometry, COUNTYFP)

us_county_Chosen <- us_county %>% # Select geometry of chosen County: Allegheny
  subset(GEOID == County_GEOID) %>%
  dplyr::select(GEOID, geometry, COUNTYFP)

ggplot() +
  geom_sf(data = State_Precinct_County_GEO_Exterior, color = "black", fill = NA) +
  geom_sf(data = us_county_Chosen, color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  theme(legend.position = "none")
```

```{r }
# Identify and select exterior precincts

Precinct_and_County_Spatial <- rbind(st_transform(us_county_Chosen, crs = CRS),
                                     st_transform(State_Precinct_County_GEO_Exterior, crs = CRS)) %>% 
  sf::as_Spatial() # Combine interior County with exterior precincts (In spatial format for matching)

Adjacent_List_Exterior <- spdep::poly2nb(sp::as.SpatialPolygons.PolygonsList(Precinct_and_County_Spatial@polygons), 
                                         snap = poly2nb_snap) # Create list of which geometries tangent which

Precinct_and_County_Spatial_sf <- rbind(st_transform(us_county_Chosen, crs = CRS),
                                     st_transform(State_Precinct_County_GEO_Exterior, crs = CRS)) # Combine interior County with exterior precincts

Precinct_Exterior <- rbind(st_transform(us_county_Chosen, crs = CRS),
                                     st_transform(State_Precinct_County_GEO_Exterior, 
                                                  crs = CRS))[Adjacent_List_Exterior[[1]],] # Subset exterior border precincts (only first entry in list necessary: "[[1]],]")

ggplot() +
  geom_sf(data = Precinct_Exterior, color = "black", fill = "gray90") +
  geom_sf(data = subset(us_county,GEOID == County_GEOID), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  theme(legend.position = "none")
```

```{r }
# Create a precinct matching data frame from exterior and interior precincts

Precinct_Exterior_crs <- st_transform(Precinct_Exterior, crs = CRS) # Consistent CRS required for matching
Precinct_Interior_crs <- st_transform(Precinct_Interior, crs = CRS)

Precinct_Border_Spatial <- rbind(Precinct_Exterior_crs, Precinct_Interior_crs) %>% 
  sf::as_Spatial() # Combine interior and exterior precincts in spatial format for matching

Adjacent_List_Border <- spdep::poly2nb(sp::as.SpatialPolygons.PolygonsList(Precinct_Border_Spatial@polygons), 
                                         snap = poly2nb_snap) # Create adjacency list for exterior and interior precincts
```

```{r }
Precinct_Relational_Data <- data.frame(Precinct1_Index = numeric(), Precinct2_Index = numeric())

for(i in 1:length(Adjacent_List_Border)){ # Create two columns in a data frame from the adjacency list
County_temp_data <- data.frame(Precinct1_Index = Adjacent_List_Border[[i]])
County_temp_data$Precinct2_Index <- i
Precinct_Relational_Data <- rbind(Precinct_Relational_Data, County_temp_data)
}
```

```{r }
Precinct_Border_crs <- rbind(Precinct_Exterior_crs, Precinct_Interior_crs) # Combine interior and exterior precincts

Precinct_County_Key <- State_Precinct %>% # Create a key of which precincts belong to which County
  as.data.frame() %>% #                     (the same as Precinct_Border_crs but has different IDs)
  dplyr::select(COUNTYFP20, GEOID20) %>% 
  dplyr::rename(GEOID = GEOID20)

# Converting index numbers into GEOID and county IDs
Precinct_Relational_Data$Precinct1_CountyCode <- Precinct_County_Key[as.numeric(Precinct_Relational_Data$Precinct1_Index),1]
Precinct_Relational_Data$Precinct2_CountyCode <- Precinct_County_Key[as.numeric(Precinct_Relational_Data$Precinct2_Index),1]

Precinct_Relational_Data$Precinct1 <- Precinct_County_Key[as.numeric(Precinct_Relational_Data$Precinct1_Index),2]
Precinct_Relational_Data$Precinct2 <- Precinct_County_Key[as.numeric(Precinct_Relational_Data$Precinct2_Index),2]

Precinct_Match_Data <- Precinct_Relational_Data %>% # Create data frame of matching precincts
  subset(Precinct1_CountyCode != Precinct2_CountyCode) %>% 
  subset(Precinct1_CountyCode == county_code | Precinct2_CountyCode == county_code) %>% # Filtering border tangents that are not of County of interest
  base::subset(Precinct2_CountyCode == county_code) # Remove duplicate marches
```

```{r }
ggplot() +
  geom_sf(data = Precinct_Exterior, color = "black", fill = "gray90") +
  geom_sf(data = Precinct_Interior, color = "black", fill = "gray90") +
  geom_sf(data = subset(us_county, GEOID == County_GEOID), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  theme(legend.position = "none")
```

```{r warning=FALSE, }
# Precinct centroids and cross County matching lines creation

Precinct_Centroid <- rbind(st_transform(Precinct_Exterior, crs = CRS), st_transform(Precinct_Interior, crs = CRS)) %>% 
  dplyr::select(GEOID, geometry) %>%
  mutate(geometry = st_point_on_surface(geometry)) # Convert border precinct shapes into centroids

length_index <- sapply(Adjacent_List_Border, length) # Convert index of list into column for data frame
length_index_vec <- numeric(0)
for (i in 1:length(length_index)) {
  vec <- numeric(length_index[i])
  vec[1:length_index[i]] <- i
  length_index_vec <- c(length_index_vec, vec)
}

df <- Adjacent_List_Border %>% # Create adjacency data frame for recessed
  unlist() %>% cbind(length_index_vec) %>% # Fully convert adjacency list into two columns
  as.data.frame() %>% 
  janitor::clean_names() %>% 
  dplyr::rename(GEOID_A = x, GEOID_B = length_index_vec) %>% 
  dplyr::mutate(COUNTY_A = Precinct_Border_Spatial$COUNTYFP[GEOID_A],
                COUNTY_B = Precinct_Border_Spatial$COUNTYFP[GEOID_B],
                GEOID_A = Precinct_Border_Spatial$GEOID[GEOID_A], 
                GEOID_B = Precinct_Border_Spatial$GEOID[GEOID_B]) %>% # Replace row IDs with precinct GEOIDs
  base::subset(COUNTY_A != COUNTY_B) %>% 
  base::subset(COUNTY_A == county_code | COUNTY_B == county_code) %>% 
  left_join(dplyr::rename(Precinct_Centroid, GEOID_A = GEOID), by = c("GEOID_A")) %>% 
  left_join(dplyr::rename(Precinct_Centroid, GEOID_B = GEOID), by = c("GEOID_B"))

mach_lines <- st_sfc(mapply(function(a,b){st_cast(st_union(a,b),"LINESTRING")}, 
                                df$geometry.x, df$geometry.y, SIMPLIFY=FALSE), crs = CRS) # Create lines between precinct pairs

plot_GA_Precinct_mach_lines <- ggplot() +
  geom_sf(data = Precinct_Exterior, color = "black", fill = "gray90") +
  geom_sf(data = Precinct_Interior, color = "black", fill = "gray80") +
  geom_sf(data = subset(us_county, GEOID == County_GEOID), color = "red", fill = NA) +
  geom_sf(data = mach_lines, color = "blue", fill = "gray90") +
  geom_sf(data = Precinct_Centroid, color = "black", fill = "gray90") +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  ggtitle("Fulton")+
  theme(legend.position = "none")
```

## GA Precinct difference analysis
```{r }
# Create blockgroup matching pairs

length_index <- sapply(Adjacent_List_Border, length)
length_index_vec <- numeric(0)
for (i in 1:length(length_index)) {
  vec <- numeric(length_index[i])
  vec[1:length_index[i]] <- i
  length_index_vec <- c(length_index_vec, vec)
}

Adjacent_Border <- Adjacent_List_Border %>% 
  unlist() %>% 
  cbind(length_index_vec) %>% 
  as.data.frame() %>% 
  janitor::clean_names() %>% 
  dplyr::rename(GEOID_A = x, GEOID_B = length_index_vec) %>% 
  dplyr::mutate(COUNTY_A = Precinct_Border_Spatial$COUNTYFP[GEOID_A],
                COUNTY_B = Precinct_Border_Spatial$COUNTYFP[GEOID_B],
                GEOID_A = Precinct_Border_Spatial$GEOID[GEOID_A], 
                GEOID_B = Precinct_Border_Spatial$GEOID[GEOID_B]) %>% 
  base::subset(COUNTY_A != COUNTY_B) %>% 
  base::subset(COUNTY_B == county_code)
```

## GA Precinct difference analysis
```{r }
# Aggregate block level census data to precinct level

State_Precinct_County_Spatial <- State_Precinct_County %>% 
  sf::as_Spatial()
Adjacent_Precinct_County <- spdep::poly2nb(sp::as.SpatialPolygons.PolygonsList(State_Precinct_County_Spatial@polygons), 
                                         snap = poly2nb_snap)


Wall_conglomerate_Precinct <- State_Precinct %>% # Select precincts in all counties
  base::subset(COUNTYFP20 %in% unique(c(Precinct_Exterior_crs$COUNTYFP, Precinct_Interior_crs$COUNTYFP))) %>% 
  st_transform(crs = CRS) %>% 
  dplyr::rename(GEOID = GEOID20, COUNTYFP = COUNTYFP20)

# Block aggregation
census_block_variables <- c("P3_001N", "P3_004N", "P3_006N", "P4_002N", "P3_009N") # Census block variables for aggregation

# census_block_data <- tidycensus::get_decennial(geography = "block",
#                     variables = census_block_variables,
#                     year = 2020,
#                     # summary_var = "P001001",
#                     state = "13",
#                     county = unique(Wall_conglomerate_Precinct$COUNTYFP),
#                     geometry = FALSE) %>%
#   pivot_wider(names_from = variable,
#               values_from = c(value))
# library(openxlsx)
# census_block_data %>%
#   openxlsx::write.xlsx(file = "GA/census_block_data_GA.xlsx", rowNames = FALSE, overwrite = TRUE)
census_block_data <- read_excel("GA/census_block_data_GA.xlsx") # Read census data

sf::sf_use_s2(FALSE) # This is required to fix an error (does not appear to affect results)
PennsylvaniaBlocks <- sf::st_read("GA/GA_Block") %>% 
  dplyr::rename(GEOID20_census = GEOID20) %>% 
  right_join(dplyr::select(census_block_data, c("GEOID", census_block_variables)), by = c("GEOID20_census" = "GEOID")) # Combine Census data with block geography

County_blocks <- base::subset(PennsylvaniaBlocks, COUNTYFP20 %in% unique(Wall_conglomerate_Precinct$COUNTYFP)) %>% # Select blocks for all relevant counties
  st_transform(crs = CRS) %>% 
  dplyr::mutate(area_original = st_area(geometry)) # Measure the original area of the blocks

Block_overlap <- sf::st_intersection(Wall_conglomerate_Precinct, County_blocks) %>% # Area Calculation
  dplyr::mutate(area_modified = st_area(geometry), area_multiplier = as.numeric(area_modified / area_original)) %>% 
  sf::st_drop_geometry() # Trims blocks into respective precincts and assigns precinct ID to block
Block_overlap$area_multiplier[Block_overlap$area_multiplier > 1] <- 1 # Fixes apparent rounding error
Block_overlap[census_block_variables] <- Block_overlap[,census_block_variables] * Block_overlap[,"area_multiplier"] # Adjusts variables by proportion of precinct overlap

Block_overlap_summarise <- Block_overlap %>% # Sum blocks to precinct level
  dplyr::group_by(GEOID) %>% 
  dplyr::summarise_at(vars(census_block_variables), sum, na.rm=TRUE) %>% 
  right_join(Wall_conglomerate_Precinct, by = c("GEOID" = "GEOID")) %>% 
  as.data.frame() %>% 
  dplyr::mutate(Minority = (P3_004N + P3_006N + P4_002N) / P3_001N, # Create minority variable and addreess undefined values
                Minority = ifelse(is.infinite(Minority), 0, Minority),
                Minority = ifelse(is.nan(Minority), 0, Minority))

Block_overlap_summarise$Exterior_ <- ifelse(Block_overlap_summarise$COUNTYFP == county_code,
                                 "Interior", "Exterior")

ggplot() + # Observe block aggregation
  geom_sf(data = Block_overlap_summarise, color = "black", aes(fill = Minority, geometry = geometry)) +
  geom_sf(data = subset(us_county, GEOID == County_GEOID), color = "red", fill = NA) +
  coord_sf()+
  scale_fill_viridis(discrete = FALSE)+
  ggtitle("Allegheny")
```

```{r}
# Block group variables

All_COUNTYFP <- unique(Precinct_Border_crs$COUNTYFP) # Vector of all county codes

census_BlockGroup_variables <- c(
                            "B28002_001", # Internet Access (Estimate!!Total:)
                            "B28002_013", # Internet Access (Estimate!!Total:!!No Internet access)
                            "B01002_001",	# Estimate!!Median age --!!Total
                            "B19013_001",	# Estimate!!Median household income in the past 12 months (in 2020 inflation-adjusted dollars)
                            
                            "B25045_001", # Estimate!!Total:
                            "B25045_012", # Estimate!!Total:!!Renter occupied:!!No vehicle available:
                            "B25045_003", # Estimate!!Total:!!Owner occupied:!!No vehicle available:
                            "B14007_001", # SCHOOL ENROLLMENT BY DETAILED  LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER: Total:
                            "B14007_002" # SCHOOL ENROLLMENT BY DETAILED  LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER: Enrolled in school:
                            ) # Census block variables for aggregation
# tidycensus::get_acs(geography = "block group", # Un-comment to re-download data
#                     variables = census_BlockGroup_variables,
#                     year = 2020,
#                     state = "13",
#                     county = All_COUNTYFP,
#                     geometry = FALSE,
#                     survey = "acs5",
#                     cache_table = TRUE) %>%
#   dplyr::select(!moe) %>%
#   pivot_wider(names_from = variable,
#               values_from = c(estimate)) %>%
#   openxlsx::write.xlsx(file = BlockGroup_data_file, rowNames = FALSE, overwrite = TRUE)
census_BlockGroup_data <- read_excel(BlockGroup_data_file) %>% # Read census block group data
  dplyr::rename(Age = B01002_001, income = B19013_001) %>% 
  dplyr::mutate_all(.funs = list(~ ifelse(is.na(.) == TRUE, rnorm( # Replace missing values with randomized median
    sum(is.na(.) == TRUE), 
    mean = median(., na.rm = TRUE), 
    sd = sd(., na.rm = TRUE)), .)))

census_BlockGroup_variables <- c("Age", "income", "B28002_013", "B28002_001", # Redefine variable list
                                 "B25045_001", "B25045_012", "B25045_003",
                                 "B14007_001", "B14007_002")

sf::sf_use_s2(FALSE) # This is required to fix an error (does not appear to affect results)
County_BlockGroup <- sf::st_read(BlockGroup_shapefile) %>%
  dplyr::rename(GEOID20_census = GEOID) %>% 
  right_join(census_BlockGroup_data, by = c("GEOID20_census" = "GEOID")) %>% # Combine Census data with block geography
  base::subset(COUNTYFP %in% All_COUNTYFP) %>% # Select blocks for all relevant counties
  st_transform(crs = CRS) %>% 
  dplyr::mutate(area_original = st_area(geometry)) # Measure the original area of the blocks

BlockGroup_overlap <- sf::st_intersection(Wall_conglomerate_Precinct, County_BlockGroup) %>% # Area Calculation
  dplyr::mutate(area_modified = st_area(geometry), area_multiplier = as.numeric(area_modified / area_original)) %>%
  sf::st_drop_geometry() # Trims blocks into respective precincts and assigns precinct ID to block
BlockGroup_overlap$area_multiplier[BlockGroup_overlap$area_multiplier > 1] <- 1 # Fixes apparent rounding error
BlockGroup_overlap[census_BlockGroup_variables] <- BlockGroup_overlap[,census_BlockGroup_variables] * BlockGroup_overlap[,"area_multiplier"] # Adjusts variables by proportion of precinct overlap

Block_overlap_summarise <- BlockGroup_overlap %>% # Sum blocks to precinct level
  dplyr::group_by(GEOID) %>% 
  dplyr::summarise_at(vars(census_BlockGroup_variables), sum, na.rm = TRUE) %>% 
  dplyr::select(c("GEOID"), census_BlockGroup_variables) %>% 
  right_join(Block_overlap_summarise, by = "GEOID") %>% 
  as.data.frame() %>% 
  dplyr::mutate(Internet = B28002_013 / B28002_001, # Create proportion variables and replace undefined values
                Internet = ifelse(is.infinite(Internet), 0, Internet),
                vehicle = (B25045_012 + B25045_003) / B25045_001,
                vehicle = ifelse(is.infinite(vehicle), 0, vehicle),
                School = B14007_002 / B14007_001,
                School = ifelse(is.infinite(School), 0, School))

census_block_variables = c("Minority", "Age", "income", "Internet", "vehicle", "School") # Redefine census variable list
```

```{r}
# Observe block group variables and aggregation

ggplot() +
  geom_sf(data = County_BlockGroup, color = "black", aes(fill = (B25045_012 + B25045_003) / B25045_001, geometry = geometry)) +
  geom_sf(data = subset(us_county, GEOID %in% c("13113", "13135", "13117", "13063", "13097", "13077", 
                                                "13045", "13057", "13067", "13089", "13121")), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = FALSE)+
  theme(legend.position = "none")

ggplot() +
  geom_sf(data = Block_overlap_summarise, color = "black", aes(fill = vehicle, geometry = geometry)) +
  geom_sf(data = subset(us_county, GEOID %in% c("13113", "13135", "13117", "13063", "13097", "13077", 
                                                "13045", "13057", "13067", "13089", "13121")), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = FALSE)+
  theme(legend.position = "none")
```

#
```{r }
# Precinct matching pairs
length_index <- sapply(Adjacent_List_Border, length)

length_index_vec <- numeric(0)

for (i in 1:length(length_index)) {
  vec <- numeric(length_index[i])
  vec[1:length_index[i]] <- i
  length_index_vec <- c(length_index_vec, vec)
}

Adjacent_Border <- Adjacent_List_Border %>% 
  unlist() %>% 
  cbind(length_index_vec) %>% 
  as.data.frame() %>% 
  janitor::clean_names() %>% 
  dplyr::rename(GEOID_A = x, GEOID_B = length_index_vec) %>% 
  dplyr::mutate(COUNTY_A = Precinct_Border_Spatial$COUNTYFP[GEOID_A],
                COUNTY_B = Precinct_Border_Spatial$COUNTYFP[GEOID_B],
                GEOID_A = Precinct_Border_Spatial$GEOID[GEOID_A], 
                GEOID_B = Precinct_Border_Spatial$GEOID[GEOID_B]) %>% 
  base::subset(COUNTY_A != COUNTY_B) %>% 
  base::subset(COUNTY_B == county_code)
```

## Absentee data
```{r }
# Translation tables
Absentee_variables <- c("precinct", "County",
  "jb_election_day", "jb_absentee", "jb_provisional",
  "dt_election_day",   "dt_absentee", "dt_provisional",
  "ind_election_day", "ind_absentee", "ind_provisional",
  "total_election_day", "total_absentee", "total_provisional",
  "total_votes", "GEOID20", "Border")
Conglomerate_Absentee <- read_excel("GA/Fulton_Conglomerate_Absentee.xlsx") %>% # Read election results data and create relevant variables
  dplyr::mutate(total_election_day = jb_election_day + dt_election_day + ind_election_day,
                total_absentee = jb_absentee + dt_absentee + ind_absentee,
                total_provisional = jb_provisional + dt_provisional + ind_provisional) %>% 
  dplyr::select(all_of(Absentee_variables)) %>% 
  mutate(Porp_Absentee = total_absentee / total_votes,
         Porp_Trump = (dt_election_day + dt_absentee + dt_provisional) / total_votes,
         Porp_Trump_Absentee = dt_absentee / total_absentee,
         Porp_Trump_election_day = dt_election_day / total_election_day,
         
         Porp_Absentee = replace(Porp_Absentee, is.nan(Porp_Absentee), 0),
         Porp_Trump = replace(Porp_Trump, is.nan(Porp_Trump), 0),
         Porp_Trump_Absentee = replace(Porp_Trump_Absentee, is.nan(Porp_Trump_Absentee), 0),
         Porp_Trump_election_day = replace(Porp_Trump_election_day, is.nan(Porp_Trump_election_day), 0)) %>% 
  dplyr::mutate(County_CAP = toupper(County))
Conglomerate_Absentee$county_party <- with(Conglomerate_Absentee, 
                                                  ifelse(County_CAP == "FULTON", "Fulton", 
          ifelse(County_CAP %in% c("CARROLL", "CHEROKEE", "COWETA", "FORSYTH", "FAYETTE"), "Republican", "Democrat")))

Conglomerate_Absentee_variables <- c("Porp_Absentee", "Porp_Trump", "Porp_Trump_Absentee", "Porp_Trump_election_day")

Conglomerate_Absentee_data <- Conglomerate_Absentee %>% 
  dplyr::left_join(dplyr::select(Block_overlap_summarise, c("GEOID", census_block_variables)),
                   by = c("GEOID20" = "GEOID")) %>% 
  dplyr::distinct(GEOID20, .keep_all = TRUE) %>% 
  dplyr::mutate(GEOID20 = as.character(GEOID20))
```

```{r}
Conglomerate_Absentee_Border <- Conglomerate_Absentee_data %>% 
  subset(Border == "Border") %>% 
  dplyr::mutate(county_party = factor(county_party, 
                                       levels = c("Fulton", "Democrat", "Republican"),
                                      labels = c("Fulton", "Democrat County", "Republican County")))
```

```{r}
plot_GA_Abs_EDV_UP <- ggplot(Conglomerate_Absentee_Border, 
                                                    aes(y = Porp_Trump_Absentee, x = Porp_Trump_election_day, color = county_party))+
  geom_point()+
  theme_light()+
  ggtitle("Figure 2: Trump % Absentee Vs Election-Day Vote; Fulton & Surrounding County Border Precincts")+
  labs(y = "% of Mail-In Votes for Trump out of Total Mail-In Ballots Cast",
       x = "% of Election-Day Votes for Trump out of Total Election-Day Ballots Cast",
       subtitle = "2020 Presidential Election",
       caption = quote(NULL),
       color = "Border Precincts")+
  theme(legend.position='top')+
  scale_y_continuous(labels = scales::percent)+
  scale_x_continuous(labels = scales::percent)+
  scale_colour_manual(values=c("darkblue", "cyan3", "firebrick1"))
plot_GA_Abs_EDV_UP
```

## Match analysis
```{r }
mach_O <- Conglomerate_Absentee_data %>%  # Combine outer precincts with data
  dplyr::select(c("GEOID20", Conglomerate_Absentee_variables, census_block_variables)) %>% 
  dplyr::right_join(dplyr::select(Adjacent_Border, GEOID_A), by = c("GEOID20" = "GEOID_A")) %>% 
  dplyr::select(!GEOID20)

mach_I <- Conglomerate_Absentee_data %>%  # Combine inner precincts with data
  dplyr::select(c("GEOID20", Conglomerate_Absentee_variables, census_block_variables)) %>% 
  dplyr::right_join(dplyr::select(Adjacent_Border, GEOID_B), by = c("GEOID20" = "GEOID_B")) %>% 
  dplyr::select(!GEOID20)

Precinct_match_data <- (mach_I - mach_O) %>% na.omit # Appears to be inner precincts minus outer precincts
```

## GA Berlin Wall Test (Precinct)
```{r }
State_Precinct_County_Spatial <- State_Precinct_County %>% # Convert precincts to spatial format for matching
  sf::as_Spatial()

Adjacent_Precinct_County <- spdep::poly2nb(sp::as.SpatialPolygons.PolygonsList(State_Precinct_County_Spatial@polygons), 
                                         snap = poly2nb_snap) # Initialize matching list

# precinct matching pairs
length_index <- sapply(Adjacent_Precinct_County, length) # Create matched precinct column
length_index_vec <- numeric(0)
for (i in 1:length(length_index)) {
  vec <- numeric(length_index[i])
  vec[1:length_index[i]] <- i
  length_index_vec <- c(length_index_vec, vec)
}

Adjacent_Precinct_County <- Adjacent_Precinct_County %>% # Create inner ring match list
  unlist() %>% cbind(length_index_vec) %>% # Create Counterpart matched precinct column
  as.data.frame() %>% 
  janitor::clean_names() %>% 
  dplyr::rename(GEOID_B = x, GEOID_C = length_index_vec) %>%
  dplyr::mutate(GEOID_B = State_Precinct_County$GEOID20[GEOID_B],
                GEOID_C = State_Precinct_County$GEOID20[GEOID_C]) %>% 
  base::subset(GEOID_B %in% Precinct_Interior$GEOID) %>% 
  base::subset(!GEOID_C %in% Precinct_Interior$GEOID)

# Centroid initialization (for plots)
Precinct_Centroid_2nd <- rbind(st_transform(subset(State_Precinct_County, 
                                                   GEOID20 %in% unique(Adjacent_Precinct_County$GEOID_C)), crs = CRS), 
                           st_transform(subset(State_Precinct_County, 
                                               GEOID20 %in% unique(Adjacent_Precinct_County$GEOID_B)), crs = CRS)) %>% 
  dplyr::select(GEOID20, geometry) %>%
  mutate(geometry = st_point_on_surface(geometry))

df <- Adjacent_Precinct_County %>% 
  left_join(dplyr::rename(Precinct_Centroid_2nd, GEOID_B = GEOID20), by = c("GEOID_B")) %>% 
  left_join(dplyr::rename(Precinct_Centroid_2nd, GEOID_C = GEOID20), by = c("GEOID_C"))

mach_lines_2nd <- st_sfc(mapply(function(a,b){st_cast(st_union(a,b),"LINESTRING")}, # Create lines for plots
                                df$geometry.x, df$geometry.y, SIMPLIFY=FALSE), crs = CRS)

# match map
Fulton_Republican_County_conversion_table <- us_county_state %>% 
  sf::st_drop_geometry() %>% 
  base::subset(toupper(NAME) %in% c("CARROLL", "CHEROKEE", "COWETA", "FORSYTH", "FAYETTE"))

Precinct_Exterior$geometry_color <- with(Precinct_Exterior, 
                                ifelse(Precinct_Exterior$COUNTYFP %in% Fulton_Republican_County_conversion_table$COUNTYFP,
                                            "Democrat", "Republican"))

Precinct_Interior$geometry_color <- "Fulton"

Precinct_Recessed <- subset(State_Precinct_County, GEOID20 %in% unique(Adjacent_Precinct_County$GEOID_C))
Precinct_Recessed$geometry_color <- "Recessed"


Precinct_All_match <- base::rbind(st_transform(dplyr::select(Precinct_Exterior, c("geometry_color", "geometry")), crs = CRS),
                                  st_transform(dplyr::select(Precinct_Interior, c("geometry_color", "geometry")), crs = CRS),
                                  st_transform(dplyr::select(Precinct_Recessed, c("geometry_color", "geometry")), crs = CRS))

# Adjacent_Precinct_County

mach_2nd <- Conglomerate_Absentee_data %>% # call inner ring Precincts
  dplyr::mutate(GEOID20 = as.numeric(GEOID20)) %>% 
  dplyr::select(c("GEOID20", Conglomerate_Absentee_variables, census_block_variables)) %>% 
  dplyr::right_join(dplyr::select(Adjacent_Precinct_County, GEOID_C), by = c("GEOID20" = "GEOID_C")) %>% 
  dplyr::select(!GEOID20)

mach_I_2 <- Conglomerate_Absentee_data %>% # call interior Precincts
  dplyr::mutate(GEOID20 = as.numeric(GEOID20)) %>% 
  dplyr::select(c("GEOID20", Conglomerate_Absentee_variables, census_block_variables)) %>% 
  dplyr::right_join(dplyr::select(Adjacent_Precinct_County, GEOID_B), by = c("GEOID20" = "GEOID_B")) %>% 
  dplyr::select(!GEOID20)

Precinct_match_data_2nd <- (mach_I_2 - mach_2nd) %>% na.omit # interior Precincts - inner ring Precincts

ggplot() +
  geom_sf(data = State_Precinct_County_GEO, color = "black", fill = "gray90") +
  coord_sf()+
  theme_void()+
  scale_fill_viridis(discrete = TRUE)+
  theme(legend.position = "none")

# Combine both rings of differences into one data frame
mach_GEOID_A <- Conglomerate_Absentee_data %>% 
  dplyr::select(c("GEOID20", Conglomerate_Absentee_variables, census_block_variables)) %>% 
  dplyr::right_join(dplyr::select(Adjacent_Border, GEOID_A), by = c("GEOID20" = "GEOID_A"))

Precinct_match_data <- (mach_I - mach_O)
Precinct_match_data$GEOID20 <- as.numeric(mach_GEOID_A$GEOID20)
Precinct_match_data <- Precinct_match_data %>% 
  left_join(dplyr::select(Conglomerate_Absentee, c("GEOID20", "county_party")), by = "GEOID20") %>% 
  dplyr::select(!GEOID20) %>% 
  dplyr::rename(ring = county_party) %>% 
  na.omit()
Precinct_match_data_2nd$ring <- "Exterior"

Precinct_match_data_3rd <- rbind(Precinct_match_data, Precinct_match_data_2nd)
Precinct_match_data_3rd$ring <- with(Precinct_match_data_3rd, 
                                                  ifelse(ring == "Exterior", "Recessed", 
          ifelse(ring == "Republican", "Exterior Republican", "Exterior Democrat")))
Precinct_match_data_3rd$ring <- factor(Precinct_match_data_3rd$ring, 
                                       levels = c("Recessed", "Exterior Democrat", "Exterior Republican"))
```

```{r fig.height=10, fig.width=20}
plot_GA_Precinct_mach_lines <- ggplot() +
  geom_sf(data = Precinct_All_match, aes(fill = geometry_color), color = "black") +
  geom_sf(data = subset(us_county, GEOID == County_GEOID), color = "red", fill = NA) +
  geom_sf(data = mach_lines_2nd, color = "magenta3") +
  geom_sf(data = Precinct_Centroid_2nd, color = "gray15") +
  geom_sf(data = mach_lines, color = "deepskyblue1") +
  geom_sf(data = Precinct_Centroid, color = "gray15") +
  coord_sf()+
  theme_void()+
  scale_fill_manual(values=c("#d59d9e", "dodgerblue2", "dodgerblue4", "#4b78bc"))+
  ggtitle("Fulton County, Georgia") +
  labs(caption = "Figure iv") +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=35),
        plot.caption = element_text(hjust = 0.5, size=20))
plot_GA_Precinct_mach_lines

plot_GA_Precinct_Border_example <- ggplot() +
  geom_sf(data = base::subset(Precinct_All_match, geometry_color != "Recessed"), 
          aes(fill = geometry_color), color = "black") +
  geom_sf(data = subset(us_county, GEOID == County_GEOID), color = "red", fill = NA) +
  coord_sf()+
  theme_void()+
  scale_fill_manual(values=c("#d59d9e", "dodgerblue2", "#4b78bc"))+
  ggtitle("Fulton County, Georgia") +
  labs(caption = "Figure ii")+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=35),
        plot.caption = element_text(hjust = 0.5, size=20))
plot_GA_Precinct_Border_example
```

```{r }
# Exterior and Recessed differences
plot_GA_Abs_EDV_Diff <- ggplot(Precinct_match_data_3rd, 
                                                    aes(y = Porp_Trump_Absentee, x = Porp_Trump_election_day, color = ring))+
  geom_point()+
  theme_light()+
  ggtitle("Figure 4: Difference in Trump Absentee Vs In-Person Share; Fulton Exterior & Recessed Paired Precincts")+
  labs(y = "Difference in % of Mail-In Ballots for Trump", 
       x = "Difference in % of Election-Day Ballots for Trump",
       subtitle = "Across Adjacent Precincts, 2020 Presidential Election",
       caption = quote(NULL),
       color = "Precinct Difference")+
  scale_colour_manual(values=c("deepskyblue4", "#417ddd", "#c84c42"))+
  scale_y_continuous(labels = scales::percent)+
  scale_x_continuous(labels = scales::percent)+
  theme(legend.position='top')
plot_GA_Abs_EDV_Diff
```

```{r}
save(Conglomerate_Absentee_Border,
     Precinct_match_data_3rd,
          file = "GA/GA_model_data.Rdata")

save(plot_GA_Precinct_Border_example,
     plot_GA_Precinct_mach_lines, 
     plot_GA_Abs_EDV_UP,
     plot_GA_Abs_EDV_Diff,
          file = "GA/GA_plots.Rdata")
```